[package]
name = "employee"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = "2.0.0"
rsfbclient-diesel = "0.21.0"
argopt = "0.3.0"
tabled = "0.8.0"

[workspace]